platform :ios, '10.0'

use_frameworks!

target 'CommonLibrary_Example' do
  pod 'CommonLibrary', :path => '../'
  
  pod 'KeychainAccess'
  pod 'MSAL'
  
  target 'CommonLibrary_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
